import {getLocale} from "next-intl/server";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();

  return (
    <html lang={locale} dir={locale == "ar" ? "rtl" : "ltr"}>
      <body>{children}</body>
    </html>
  );
}
